### PR TITLE
Allow more frequent restores

### PR DESCRIPTION
**Pull request by bradym**
First, thank you for building and sharing this tool. It works very well and is a huge time saver.

I'm using this to create a stage database for one of our products. For a staging database it is useful to be able to restore as frequently as needed. For example when writing code or testing a task that changes a significant amount of data it is useful to test the code against a fresh copy of the database, do verification of the feature, make more changes, and then test the code against another fresh copy of the database.

Given the prescribed workflow this tool uses and the `today_string` variable being hard-coded to the current day, it's not possible to use this tool for that purpose without manually deleting the existing database. I'd much prefer to rely on the logic built into this tool to handle that so I don't have to have a separate tool for that.

This PR makes two changes:

- Adds a flag to the `new` and `clone` commands to allow you to pass in a value to use for the `today_string` variable.
- Changes `minimum_age_hours` from an int to a float to allow for values like .5 to enable more frequent changes.

Please let me know if you have any questions/concerns about this approach.

### CODE REVIEW

**Comment by whwright** [comment]
Hello! Thank you for the contribution.

I find the solution to change the value of `today_string` a bit counterintuitive. We know what the value of "today" is, so IMO this should not be configurable.

However, I do see your use case as valid. What do you think about using a flag on the CLI to use a `datetime` for the suffix to the cluster name? This would allow you to create a new cluster every second, but also not change the default behavior for anyone who upgrades.

**Comment by bradym** [comment]
Thanks for the feedback, I see your point about using `today_string` that way. Rather than a flag that adds the time as a suffix, would it be better to just have a an optional --suffix flag that allows the user to specify what it should be? 

I'm not set on either approach, just thought this might match some use cases that haven't been considered and prevent extra work for it later.

**Comment by whwright** [comment]
I am okay with a `--suffix` parameter.

Anyone else have an opinion? @megallo @rdooley @ruhul-blacklocus @blacklocus/core

**Comment by bradym** [comment]
Sounds good, I'll update my PR to add the `--suffix` parameter and revert my changes that modified `today_string`

**Pull request closed without merging**
