### PR TITLE
Allow more frequent restores - new version

### PR DESCRIPTION
**Pull request by bradym**
This addresses the feedback from https://github.com/blacklocus/aurora-echo/pull/11 - i didn't mean to close that other PR, sorry for any confusion this causes.

Let me know if you have any other feedback on this one.

### CODE REVIEW

**Review by whwright — APPROVED** [review]
:+1:

**Review by ruhul-blacklocus — APPROVED** [review]
👍 👍

**Review by megallo — APPROVED** [review]
:+1: :+1: :+1:

**Review by rdooley — COMMENTED** [review]
:+1: :+1: :+1: :+1:

**Comment by whwright** [comment]
I will work on publishing a new release this evening

**Comment by whwright** [comment]
This change is in release v2.1.1 https://github.com/blacklocus/aurora-echo/releases/tag/v2.1.1

Thanks for the contribution!

**Pull request merged**
